name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    name: 'macOS'
    runs-on: [ macos-latest ]

    steps:

      - uses: actions/checkout@v2

      - name: Prepare
        run: brew install conan

      - name: Run conan
        run: conan install . --build=missing

      - name: Cmake
        run: cmake --preset conan-release

      - name: Compile
        run: cmake --build --preset conan-release

      - name: Pack
        run: |
          {
            mv ./build/Release/yaschperitsy .
            tar -czvf yaschperitsy_macos.tar.gz yaschperitsy assets
          }

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yaschperitsy_macos
          path: yaschperitsy_macos.tar.gz

  windows-msvc:

    name: Windows (MSVC)
    runs-on: [ windows-latest ]

    steps:

      - uses: actions/checkout@v2

      - name: Boost
        run: choco install conan

      - name: Run conan
        run: conan install . --build=missing

      - name: Cmake
        run: cmake --preset conan-release

      - name: Compile
        run: cmake --build --preset conan-release

      - name: Pack
        run: |
          mkdir yaschperitsy
          mv ./build/Release/yaschperitsy.exe yaschperitsy/
          mv ./assets yaschperitsy/

          mv ./SDL2/SDL2-2.30.3/lib/x64/SDL2.dll yaschperitsy/
          mv ./SDL2_image/SDL2_image-2.8.2/lib/x64/SDL2_image.dll yaschperitsy/
          mv ./SDL2_ttf/SDL2_ttf-2.22.0/lib/x64/SDL2_ttf.dll yaschperitsy/

          Compress-Archive -Path ./yaschperitsy -DestinationPath ./yaschperitsy_win.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yaschperitsy_win
          path: ./yaschperitsy_win.zip
