name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    name: 'macOS'
    runs-on: [ macos-latest ]

    steps:

      - uses: actions/checkout@v2

      - name: Prepare
        run: brew install SDL2 SDL2_image SDL2_ttf boost

      - name: Compile
        run: |
          {
            mkdir build
            cd build
            cmake ..
            cmake --build .
          }

      - name: Test
        run: ./build/yaschperitsy_test

      - name: Pack
        run: |
          {
            mv ./build/yaschperitsy .
            tar -czvf yaschperitsy_macos.tar.gz yaschperitsy assets
          }

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yaschperitsy_macos
          path: yaschperitsy_macos.tar.gz

  windows-msvc:

    name: Windows (MSVC)
    runs-on: [ windows-latest ]

    steps:

      - uses: actions/checkout@v2

      - name: Download SDLs
        run: |
          curl.exe -JLO https://github.com/libsdl-org/SDL/releases/download/release-2.30.3/SDL2-devel-2.30.3-VC.zip
          curl.exe -JLO https://github.com/libsdl-org/SDL_image/releases/download/release-2.8.2/SDL2_image-devel-2.8.2-VC.zip
          curl.exe -JLO https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.22.0/SDL2_ttf-devel-2.22.0-VC.zip
          curl.exe -JLO https://archives.boost.io/release/1.82.0/source/boost_1_82_0.zip
          Expand-Archive ./SDL2-devel-2.30.3-VC.zip -DestinationPath ./SDL2
          Expand-Archive ./SDL2_image-devel-2.8.2-VC.zip -DestinationPath ./SDL2_image
          Expand-Archive ./SDL2_ttf-devel-2.22.0-VC.zip -DestinationPath ./SDL2_ttf
          Expand-Archive ./boost_1_82_0.zip -DestinationPath ./boost

      - name: Cmake
        run: |
          mkdir build
          cd build
          cmake .. -DSDL2_INCLUDE_DIRS="./SDL2/SDL2-2.30.3/include;./SDL2_image/SDL2_image-2.8.2/include;./SDL2_ttf/SDL2_ttf-2.22.0/include" -DSDL2_LIBRARIES="SDL2;SDL2main;SDL2_image;SDL2_ttf" -DSDL2_LIB_DIRS="./SDL2/SDL2-2.30.3/lib/x64;./SDL2_image/SDL2_image-2.8.2/lib/x64;./SDL2_ttf/SDL2_ttf-2.22.0/lib/x64"
          cmake --build .

      - name: Pack
        run: |
          mkdir yaschperitsy
          mv ./build/Debug/yaschperitsy.exe yaschperitsy/
          mv ./assets yaschperitsy/

          mv ./SDL2/SDL2-2.30.3/lib/x64/SDL2.dll yaschperitsy/
          mv ./SDL2_image/SDL2_image-2.8.2/lib/x64/SDL2_image.dll yaschperitsy/
          mv ./SDL2_ttf/SDL2_ttf-2.22.0/lib/x64/SDL2_ttf.dll yaschperitsy/

          Compress-Archive -Path ./yaschperitsy -DestinationPath ./yaschperitsy_win.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yaschperitsy_win
          path: ./yaschperitsy_win.zip

# name: CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   ubuntu64:
#     name: 'Linux/Ubuntu 64-bit'
#     runs-on: [ ubuntu-latest ]

#     steps:

#       - uses: actions/checkout@v2

#       - name: Prepare
#         run: sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

#       - name: Compile
#         run: make

#       - name: Upload Artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: my-artifact-ubuntu
#           path: game

#   windows-mingw:
#     name: Windows (MinGW)
#     runs-on: windows-latest
#     defaults:
#       run:
#         shell: msys2 {0}
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         submodules: true

#     - name: Set up MSYS2
#       uses: msys2/setup-msys2@v2
#       with:
#         msystem: mingw32
#         install: >-
#           mingw-w64-i686-cc
#           mingw-w64-i686-cmake
#           mingw-w64-i686-make
#           mingw-w64-i686-ninja
#           mingw-w64-i686-pkg-config
#           mingw-w64-i686-SDL2

#     - name: CMake configure (Debug)
#       run: make win


#   # win64:
#   #   name: 'Windows 64-bit'
#   #   runs-on: [ windows-latest ]

#   #   steps:

#   #     - uses: actions/checkout@v2

#   #     - name: Download SDL if not cached
#   #       run: |
#   #         if (-Not (Test-Path C:\SDL))
#   #         {
#   #           Invoke-WebRequest "https://github.com/libsdl-org/SDL/releases/download/release-2.30.3/SDL2-devel-2.30.3-VC.zip" -OutFile C:\SDL.zip
#   #           Expand-Archive C:\SDL.zip -DestinationPath C:\
#   #         }

#   #     - name: Prepare
#   #       run: |
#   #         {
#   #           Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
#   #           Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
#   #           scoop install gcc make
#   #         }

#   #     - name: Compile
#   #       run: make win

#   #     - name: Create a file
#   #       run: dir C:\SDL2-2.30.3\include > my-file_windows.txt
#   #     - name: Upload Artifact
#   #       uses: actions/upload-artifact@v4
#   #       with:
#   #         name: my-artifact-windows
#   #         path: my-file_windows.txt

